plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  
gh_edit_link: false
color_scheme: dark
aux_links:
  "Source Code":
    - "//github.com/CatraProto/Client"
    
    
---
layout: default
title: What is CatraProto?
nav_order: 4
---

remote_theme: just-the-docs/just-the-docs
